package com.pratica.backend.repository;

import com.pratica.backend.model.Task;
import com.pratica.backend.model.Status;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

@Repository
public class TaskRepository {

    private final JdbcTemplate jdbcTemplate;

    public TaskRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public Task save(Task task) {
        String sql = " INSERT INTO tarefas (descricao, status, data_limite) VALUES (?, ?, ?)";

        // 1-Creates the keyHolder(Porta-Chaves) null to capture the ID that the database will generate
        KeyHolder keyHolder = new GeneratedKeyHolder();

        // 2-It uses a different version of the update that accepts keyHolder
        jdbcTemplate.update(connection -> {
            // Prepare the SQL statement and prompt: Return the generated key (ID)
            PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, task.getDescription());
            ps.setString(2, task.getStatus().name());// uses the 'name()' to extract the word the Enum in String
            ps.setObject(3, task.getDateLimit());
            return ps;
        }, keyHolder);

        // 3-Get the key fob ID and put it into the Java object.
        if (keyHolder.getKeys() != null) {
            // Converts the ID generated by PostgreSQL to a Long and injects it into the task.
            task.setId(((Number) keyHolder.getKeys().get("id")).longValue());
        }

        return task;
    }

    public List<Task> findAll() {
        String sql = "SELECT * FROM tarefas";

        return jdbcTemplate.query(sql, taskRowMapper);
    }

    public Task update(Task task) {
        String sql = "UPDATE tarefas SET descricao = ?, status = ?, data_limite = ? WHERE id = ?";

        jdbcTemplate.update(sql,
                task.getDescription(),
                task.getStatus().name(),
                task.getDateLimit(),
                task.getId() // The ID entered last to match the WHERE clause
        );

        return task;
    }

    public void delete(Long id) {
        String sql = "DELETE FROM tarefas WHERE id = ?";

        jdbcTemplate.update(sql, id);
    }

    public java.util.Optional<Task> findById(Long id) {
        String sql = "SELECT * FROM tarefas WHERE id = ?";

        return jdbcTemplate.query(sql, taskRowMapper, id).stream().findFirst();
    }

    public List<Task> findByStatus(Status status) {
        String sql = "SELECT * FROM tarefas WHERE status = ?";

        return jdbcTemplate.query(sql, taskRowMapper, status.name());
    }

    public List<Task> findByDateLimit(java.time.LocalDate dateLimit) {
        String sql = "SELECT * FROM tarefas WHERE data_limite = ?";

        return jdbcTemplate.query(sql, taskRowMapper, dateLimit);
    }
    /**
     * Mapeador de linhas do ResultSet para a entidade Task.
     * Funciona como uma ponte que traduz os dados relacionais vindos do banco de dados
     * para instâncias do nosso objeto Java, lidando com o "descasamento de impedância".
     */
    private final RowMapper<Task> taskRowMapper = (rs, rowNum) -> {
        Task task = new Task();

        task.setId(rs.getLong("id"));
        task.setDescription(rs.getString("descricao"));
        task.setStatus(Status.valueOf(rs.getString("status")));
        task.setDateLimit(rs.getObject("data_limite", java.time.LocalDate.class));

        return task;
    };
}

