spring.application.name=To-Do-List
# Configuração de Conexão com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_tasks
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver