package com.pratica.backend.repository;

import com.pratica.backend.model.Status;
import com.pratica.backend.model.Task;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
public class TaskRepositoryTest {

    @Autowired
    private TaskRepository taskRepository;

    @Test
    void deveSalvarEBuscarUmaTarefaComSucesso() {
        // 1-Preparação (Arrange)
        Task novaTarefa = new Task();
        novaTarefa.setDescription("testing the save method");
        novaTarefa.setStatus(Status.PENDENTE);
        novaTarefa.setDateLimit(LocalDate.now().plusDays(5));

        // 2-Ação (Act)
        Task tarefaSalva = taskRepository.save(novaTarefa);

        // 3-Verificação (Assert)
        assertNotNull(tarefaSalva.getId(), "The ID generated by the database cannot be null.");
        assertEquals("testing the save method", tarefaSalva.getDescription());
    }

    @Test
    void deveAtualizarUmaTarefaComSucesso() {
        // 1
        Task novaTarefa = new Task();
        novaTarefa.setDescription("testing the update method");
        novaTarefa.setStatus(Status.PENDENTE);
        novaTarefa.setDateLimit(LocalDate.now().plusDays(2));

        Task tarefaSalva = taskRepository.save(novaTarefa);
        //2
        tarefaSalva.setDescription("testing the change in description");
        tarefaSalva.setStatus(Status.EM_PROGRESSO);
        tarefaSalva.setDateLimit(LocalDate.now().plusDays(10));
        taskRepository.update(tarefaSalva);

        Task tarefaModificada = taskRepository.findById(tarefaSalva.getId()).orElse(null);
        //3
        assertNotNull(tarefaModificada, "the task should not be null");
        assertEquals("testing the change in description", tarefaModificada.getDescription());
        assertEquals(Status.EM_PROGRESSO, tarefaModificada.getStatus());
        assertEquals(LocalDate.now().plusDays(10), tarefaModificada.getDateLimit());

    }

    @Test
    void deveDeletarUmaTarefaComSucesso() {

        Task tarefaDeletar = new Task();
        tarefaDeletar.setDescription("task to be deleted");
        tarefaDeletar.setStatus(Status.CONCLUIDA);
        tarefaDeletar.setDateLimit(LocalDate.now());

        Task tarefaSalva = taskRepository.save(tarefaDeletar);

        taskRepository.delete(tarefaSalva.getId());

        java.util.Optional<Task> tarefaBuscada = taskRepository.findById(tarefaSalva.getId());
        assertTrue(tarefaBuscada.isEmpty(), "The task should have been deleted from the database");
    }

    @Test
    void deveBuscarTarefasPorDataLimite() {

        LocalDate dataAlvo = LocalDate.now().plusDays(10);
        LocalDate dataDiferente = LocalDate.now().plusDays(5);

        Task tarefaComData = new Task();
        tarefaComData.setDescription("Task with test deadline");
        tarefaComData.setStatus(Status.PENDENTE);
        tarefaComData.setDateLimit(dataAlvo);
        Task salvaComData = taskRepository.save(tarefaComData);

        Task tarefaOutraData = new Task();
        tarefaOutraData.setDescription("Task with different deadline");
        tarefaOutraData.setStatus(Status.PENDENTE);
        tarefaOutraData.setDateLimit(dataDiferente);
        taskRepository.save(tarefaOutraData);

        // 2
        List<Task> tarefasFiltradas = taskRepository.findByDateLimit(dataAlvo);

        // 3
        assertFalse(tarefasFiltradas.isEmpty(), "You should find the task by date.");

        // Check if all the tasks on the list actually have the correct due date.
        for (Task t : tarefasFiltradas) {
            assertEquals(dataAlvo, t.getDateLimit(), "The filter returned a task with the wrong date.");
        }

        // Confirm that the task with the target date is on the list.
        boolean contemTarefaTeste = tarefasFiltradas.stream()
                .anyMatch(t -> t.getId().equals(salvaComData.getId()));
        assertTrue(contemTarefaTeste, "The target task should be in the filtered list.");
    }

    @Test
    void deveBuscarTarefasPorStatus() {

        Task tarefaPendente = new Task();
        tarefaPendente.setDescription("Tarefa Pendente Teste");
        tarefaPendente.setStatus(Status.PENDENTE);
        tarefaPendente.setDateLimit(LocalDate.now().plusDays(1));
        taskRepository.save(tarefaPendente); // Essa tarefa nao deve vir na busca

        Task tarefaConcluida = new Task();
        tarefaConcluida.setDescription("Tarefa Concluída Teste");
        tarefaConcluida.setStatus(Status.CONCLUIDA);
        tarefaConcluida.setDateLimit(LocalDate.now().plusDays(2));

        Task salvaConcluida = taskRepository.save(tarefaConcluida);

        // 2.search only for completed ones
        List<Task> tarefasConcluidas = taskRepository.findByStatus(Status.CONCLUIDA);

        // 3.
        assertFalse(tarefasConcluidas.isEmpty(), "You should find at least one completed task");

        // percorre a lista e garante que NENHUMA tarefa veio com o status errado
        for (Task t : tarefasConcluidas) {
            assertEquals(Status.CONCLUIDA, t.getStatus(), "O filtro falhou e trouxe uma tarefa não concluída");
        }

        // Garante que a tarefa exata que foi criada usando o ID está dentro da lista filtrada
        boolean contemNossaTarefa = tarefasConcluidas.stream()
                .anyMatch(t -> t.getId().equals(salvaConcluida.getId()));
        assertTrue(contemNossaTarefa, "A tarefa que acabamos de salvar não apareceu na lista filtrada");
    }
}